FROM python:latest
WORKDIR /app

COPY ./api/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY ./api ./
ENV FLASK_ENV=production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]